In [1]:
def my_function(x, y):
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(2)

4

In [4]:
my_sq(4)

16

In [5]:
assert my_sq(4) == 15

AssertionError: 

In [6]:
def avg_2(x, y):
    return (x + y) / 2

In [7]:
avg_2(10, 20)

15.0

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})

In [10]:
import numba


In [11]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [12]:
my_sq

<function __main__.my_sq(x)>

In [13]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [14]:
def my_exp(x, e):
    return x ** e

In [15]:
my_exp(2, 10)

1024

In [16]:
df['a'].apply(my_exp, e=4)

0     10000
1    160000
2    810000
Name: a, dtype: int64

In [17]:
def print_me(x):
    print(x)

In [18]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [19]:
df

a   b
0  10  20
1  20  30
2  30  40

In [20]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [21]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [22]:
import numpy as np

In [23]:
def avg_3_apply(col):
    return np.mean(col)

In [24]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [25]:
df

a   b
0  10  20
1  20  30
2  30  40

In [26]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [27]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [28]:
df.apply(avg_3_apply, axis='columns')

IndexError: index 2 is out of bounds for axis 0 with size 2

In [41]:
df['a'].mean()

20.0

In [42]:
df['a'] + df['b']

0    30
1    50
2    70
dtype: int64

In [32]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN #np.NAN np.nan
    else:
        return(x + y) / 2

In [33]:
df

a   b
0  10  20
1  20  30
2  30  40

In [34]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [35]:
import numpy as np

In [36]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [37]:
df

a   b
0  10  20
1  20  30
2  30  40

In [38]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [39]:
@np.vectorize
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN #np.NAN np.nan
    else:
        return(x + y) / 2

In [40]:
avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [41]:
import numba

In [42]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return(x + y) / 2

In [43]:
avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [44]:
%%timeit
avg_2(df['a'], df['b'])

237 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
%%timeit
avg_2_mod(df['a'], df['b'])

54.8 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [46]:
%%timeit
avg_2_mod_numba(df['a'].values, df['b'].values)

5.26 µs ± 24.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
