<img src="../worley.jpeg" align="right" height="50px">

# Intro to Numpy Package

Numpy is the numerical comutation package for Python. Many of the functions are written in C so they are very fast and have great functionality.
 

In [1]:
import numpy as np

The basis of the numpy package is the numpy array. They are declared like this and can take any iterable as input:

In [4]:
a = np.array([1, 2, 3])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3])

The behavior of Numpy arrays is different to standard Python lists.

In [11]:
np_arr = np.array(range(3))
std_list = list(range(3))

print(np_arr + np_arr)
print(std_list + std_list)

print(np_arr * 2)
print(std_list * 2)

[0 2 4]
[0, 1, 2, 0, 1, 2]
[0 2 4]
[0, 1, 2, 0, 1, 2]


Numpy arrays can do what is called broadcasting. This is where element operations can be performed in one operation instead of looping though the list.

In [12]:
print([x * 2 for x in std_list])
print(np_arr * 2)

[0, 2, 4]
[0 2 4]


The difference is pure speed when it comes to large arrays and how clean the code looks. %%timeit is very useful optimise you code and get it blazin'.

In [19]:
length = 500_000
fast = np.ones(length)
slow = [1] * length

In [20]:
%%timeit
fast * 10

265 µs ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
%%timeit
[x * 10 for x in slow]

20.9 ms ± 511 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
f'{265e-6 / 20.9e-3 * 100:.02}% of the time to run the np array'

'1.3% of the time to run the np array'

Numpy arrays can have many dimensions

In [30]:
a = np.ones((3,3))
a * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

All that maths you did manually in uni...

In [33]:
np.dot(a, [1, 2, 3])

array([6., 6., 6.])

In [34]:
np.cross(a, [1, 2, 3])

array([[ 1., -2.,  1.],
       [ 1., -2.,  1.],
       [ 1., -2.,  1.]])

It can be useful to stack arrays

In [36]:
print(np.hstack((a, a)))
print(np.vstack((a, a)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
np.reshape(a, (1, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
a = np.array([np.random.randint(5) for x in range(10)])
a

array([2, 3, 3, 0, 4, 3, 0, 0, 4, 2])

In [48]:
np.where(a > 2, a, None)

array([None, 3, 3, None, 4, 3, None, None, 4, None], dtype=object)

In [49]:
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [50]:
np.argmax(a)

4

In [51]:
np.repeat(a, 3)

array([2, 2, 2, 3, 3, 3, 3, 3, 3, 0, 0, 0, 4, 4, 4, 3, 3, 3, 0, 0, 0, 0,
       0, 0, 4, 4, 4, 2, 2, 2])

In [53]:
x = [1, 2, 3, 4,  5]
y = [20, 50, 55, 70, 80]
np.interp(2.2, x, y)

51.0